# -*- coding: utf-8 -*-
"""colab_venom (1) (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0X1N_-KYPzpbCqbDv-3lJPSIuD6UyWm

**# Snake Venom Transcriptomics using Parallel Computing**

## Import Required Libraries
"""

import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

fig = plt.figure(figsize=(4, 3), facecolor='w')
plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)
plt.title("Sample Visualization", fontsize=10)

data = io.BytesIO()
plt.savefig(data)
image = F"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Sample Visualization"
display.display(display.Markdown(F"""![{alt}]({image})"""))
plt.close(fig)

"""### Install Dependencies and MPI Environment"""

!pip install pyspark biopython requests -q
print("Done ✓")

import os
import time
import pandas as pd
import numpy as np
from multiprocessing import Pool, cpu_count
from Bio import SeqIO
import warnings
warnings.filterwarnings("ignore")

os.makedirs("data", exist_ok=True)
os.makedirs("03_Results", exist_ok=True)

print("CPUs available:", cpu_count())
print("Imports done ✓")

"""## Load Transcriptomics Dataset"""

url = (
    "https://rest.uniprot.org/uniprotkb/stream"
    "?query=taxonomy_name%3Aserpentes+AND+%28keyword%3Atoxin+OR+keyword%3Avenom%29"
    "&format=fasta"
    "&size=500"
)

response = requests.get(url)
with open("data/snake_venoms.fasta", "w") as f:
    f.write(response.text)

count = response.text.count(">")
print(f"Downloaded {count} sequences ✓")

records = []

for record in SeqIO.parse("data/snake_venoms.fasta", "fasta"):
    parts = record.id.split("|")
    protein_id = parts[1] if len(parts) > 1 else record.id

    desc = record.description
    species = "Unknown"
    if "OS=" in desc:
        species = desc.split("OS=")[1].split(" OX=")[0].strip()

    records.append({
        "protein_id": protein_id,
        "species": species,
        "sequence": str(record.seq),
    })

df_raw = pd.DataFrame(records)
df_raw.to_csv("data/raw_sequences.csv", index=False)
print(f"Parsed {len(df_raw)} proteins ✓")
df_raw.head(3)

# This single function runs on EACH protein in parallel

def extract_features(row):
    seq = row["sequence"] if isinstance(row["sequence"], str) else ""
    L = len(seq)

    if L == 0:
        return None

    # Amino acid frequencies
    freq = {aa: round(seq.count(aa) / L, 4) for aa in "ACDEFGHIKLMNPQRSTVWY"}

    # Motif counts
    motif_RGD  = seq.count("RGD")
    motif_CXXC = sum(1 for i in range(L - 3) if seq[i] == "C" and seq[i+3] == "C")
    motif_CXCX = sum(1 for i in range(L - 2) if seq[i] == "C" and seq[i+2] == "C")

    return {
        "protein_id":  row["protein_id"],
        "species":     row["species"],
        "seq_length":  L,
        "freq_A": freq["A"], "freq_C": freq["C"], "freq_D": freq["D"],
        "freq_E": freq["E"], "freq_G": freq["G"], "freq_H": freq["H"],
        "freq_K": freq["K"], "freq_P": freq["P"], "freq_R": freq["R"],
        "freq_W": freq["W"],
        "motif_RGD":   motif_RGD,
        "motif_CXXC":  motif_CXXC,
        "motif_CXCX":  motif_CXCX,
    }

print("Feature function defined ✓")

rows = [row for _, row in df_raw.iterrows()]

# ── SERIAL ──────────────────────────────────────────
print("Running SERIAL extraction...")
start = time.time()
serial_results = [extract_features(row) for row in rows]
serial_time = time.time() - start
print(f"  Serial time  : {serial_time:.3f} seconds")

# ── PARALLEL (4 cores) ──────────────────────────────
print("Running PARALLEL extraction...")
start = time.time()
with Pool(processes=4) as pool:
    parallel_results = pool.map(extract_features, rows)
parallel_time = time.time() - start
print(f"  Parallel time: {parallel_time:.3f} seconds")

# ── SPEEDUP ─────────────────────────────────────────
speedup = serial_time / parallel_time
print(f"\n  Speedup      : {speedup:.2f}x faster with parallel")
print(f"  Cores used   : 4 / {cpu_count()} available")

# Repeat the dataset 50x to simulate large-scale workload
df_large = pd.concat([df_raw] * 50, ignore_index=True)
print(f"Large dataset size: {len(df_large)} proteins")

rows_large = [row for _, row in df_large.iterrows()]

# SERIAL
print("Running SERIAL...")
start = time.time()
serial_results = [extract_features(row) for row in rows_large]
serial_time = time.time() - start
print(f"  Serial time  : {serial_time:.3f} seconds")

# PARALLEL
print("Running PARALLEL...")
start = time.time()
with Pool(processes=2) as pool:   # use 2 not 4, colab only has 2 CPUs
    parallel_results = pool.map(extract_features, rows_large)
parallel_time = time.time() - start
print(f"  Parallel time: {parallel_time:.3f} seconds")

speedup = serial_time / parallel_time
print(f"\n  Speedup      : {speedup:.2f}x")
print(f"  Dataset size : {len(df_large)} proteins")

records = []

for record in SeqIO.parse("data/snake_venoms.fasta", "fasta"):
    parts = record.id.split("|")
    protein_id = parts[1] if len(parts) > 1 else record.id

    desc = record.description
    species = "Unknown"
    if "OS=" in desc:
        species = desc.split("OS=")[1].split(" OX=")[0].strip()

    records.append({
        "protein_id": protein_id,
        "species":    species,
        "sequence":   str(record.seq),
    })

df_raw = pd.DataFrame(records)
df_raw.to_csv("data/raw_sequences.csv", index=False)
print(f"Parsed {len(df_raw)} proteins ✓")
df_raw.head(3)

import matplotlib.pyplot as plt

labels = ["Serial\n(1 core)", "Parallel\n(4 cores)"]
times  = [serial_time, parallel_time]
colors = ["#d9534f", "#5cb85c"]

plt.figure(figsize=(6, 4))
bars = plt.bar(labels, times, color=colors, edgecolor="black", width=0.4)
for bar, t in zip(bars, times):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.01,
             f"{t:.3f}s", ha="center", fontsize=12, fontweight="bold")

plt.title(f"Serial vs Parallel Feature Extraction\nSpeedup = {speedup:.2f}x", fontsize=13)
plt.ylabel("Time (seconds)")
plt.tight_layout()
plt.savefig("03_Results/speedup_plot.png", dpi=150)
plt.show()
print("Speedup chart saved ✓")

df_large = pd.concat([df_raw] * 50, ignore_index=True)

# Make each protein_id unique so no duplicates
df_large["protein_id"] = df_large["protein_id"] + "_" + df_large.index.astype(str)

print(f"Original dataset : {len(df_raw):,} proteins")
print(f"Enlarged dataset : {len(df_large):,} proteins")
print("Dataset ready for parallel processing ✓")

def extract_features(row):
    seq = row["sequence"] if isinstance(row["sequence"], str) else ""
    L   = len(seq)

    if L == 0:
        return None

    freq = {aa: round(seq.count(aa) / L, 4) for aa in "ACDEFGHIKLMNPQRSTVWY"}

    motif_RGD  = seq.count("RGD")
    motif_CXXC = sum(1 for i in range(L - 3) if seq[i] == "C" and seq[i+3] == "C")
    motif_CXCX = sum(1 for i in range(L - 2) if seq[i] == "C" and seq[i+2] == "C")

    return {
        "protein_id": row["protein_id"],
        "species":    row["species"],
        "seq_length": L,
        "freq_A": freq["A"], "freq_C": freq["C"], "freq_D": freq["D"],
        "freq_E": freq["E"], "freq_G": freq["G"], "freq_H": freq["H"],
        "freq_K": freq["K"], "freq_P": freq["P"], "freq_R": freq["R"],
        "freq_W": freq["W"],
        "motif_RGD":  motif_RGD,
        "motif_CXXC": motif_CXXC,
        "motif_CXCX": motif_CXCX,
    }

print("Feature function defined ✓")

def extract_features(row):
    seq = row["sequence"] if isinstance(row["sequence"], str) else ""
    L   = len(seq)

    if L == 0:
        return None

    freq = {aa: round(seq.count(aa) / L, 4) for aa in "ACDEFGHIKLMNPQRSTVWY"}

    motif_RGD  = seq.count("RGD")
    motif_CXXC = sum(1 for i in range(L - 3) if seq[i] == "C" and seq[i+3] == "C")
    motif_CXCX = sum(1 for i in range(L - 2) if seq[i] == "C" and seq[i+2] == "C")

    return {
        "protein_id": row["protein_id"],
        "species":    row["species"],
        "seq_length": L,
        "freq_A": freq["A"], "freq_C": freq["C"], "freq_D": freq["D"],
        "freq_E": freq["E"], "freq_G": freq["G"], "freq_H": freq["H"],
        "freq_K": freq["K"], "freq_P": freq["P"], "freq_R": freq["R"],
        "freq_W": freq["W"],
        "motif_RGD":  motif_RGD,
        "motif_CXXC": motif_CXXC,
        "motif_CXCX": motif_CXCX,
    }

print("Feature function defined ✓")

rows_large = [row for _, row in df_large.iterrows()]

# ── SERIAL ──────────────────────────────────────────
print(f"Running SERIAL on {len(rows_large):,} proteins...")
start = time.time()
serial_results = [extract_features(row) for row in rows_large]
serial_time = time.time() - start
print(f"  Serial time   : {serial_time:.3f} seconds")

# ── PARALLEL ────────────────────────────────────────
print(f"Running PARALLEL on {len(rows_large):,} proteins...")
start = time.time()
with Pool(processes=2) as pool:
    parallel_results = pool.map(extract_features, rows_large)
parallel_time = time.time() - start
print(f"  Parallel time : {parallel_time:.3f} seconds")

# ── RESULT ──────────────────────────────────────────
speedup = serial_time / parallel_time
print(f"\n  Speedup       : {speedup:.2f}x faster with parallel")
print(f"  Cores used    : 2 / {cpu_count()} available")
print(f"  Dataset size  : {len(rows_large):,} proteins")

labels = ["Serial\n(1 core)", "Parallel\n(2 cores)"]
times  = [serial_time, parallel_time]
colors = ["#d9534f", "#5cb85c"]

plt.figure(figsize=(6, 5))
bars = plt.bar(labels, times, color=colors, edgecolor="black", width=0.4)

for bar, t in zip(bars, times):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.3,
        f"{t:.2f}s",
        ha="center", fontsize=13, fontweight="bold"
    )

plt.title(
    f"Serial vs Parallel Feature Extraction\n"
    f"{len(df_large):,} proteins  |  Speedup = {speedup:.2f}x",
    fontsize=12
)
plt.ylabel("Time (seconds)")
plt.ylim(0, max(times) * 1.3)
plt.tight_layout()
plt.savefig("03_Results/speedup_plot.png", dpi=150)
plt.show()
print("Speedup chart saved ✓")

import matplotlib.pyplot as plt

labels = ["Serial\n(1 core)", "Parallel\n(2 cores)"]
times  = [serial_time, parallel_time]
colors = ["#d9534f", "#5cb85c"]

plt.figure(figsize=(6, 5))
bars = plt.bar(labels, times, color=colors, edgecolor="black", width=0.4)

for bar, t in zip(bars, times):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.3,
        f"{t:.2f}s",
        ha="center", fontsize=13, fontweight="bold"
    )

plt.title(
    f"Serial vs Parallel Feature Extraction\n"
    f"{len(df_large):,} proteins  |  Speedup = {speedup:.2f}x",
    fontsize=12
)
plt.ylabel("Time (seconds)")
plt.ylim(0, max(times) * 1.3)
plt.tight_layout()
plt.savefig("03_Results/speedup_plot.png", dpi=150)
plt.show()
print("Speedup chart saved ✓")

"""# installs

"""

import pandas as pd
import time
from multiprocessing import Pool, cpu_count
records = []
for _, row in df_raw.iterrows():
    result = extract_features(row)
    if result:
        records.append(result)

df_features = pd.DataFrame(records)
print(f"df_features shape: {df_features.shape}")
df_features.head(3)

"""# pyspark

"""

sdf = spark.createDataFrame(df_features)
sdf = sdf.repartition(8)
sdf.cache()

print("Total proteins  :", sdf.count())
print("Partitions      :", sdf.rdd.getNumPartitions())

print("\nRecords per partition:")
sdf.rdd.mapPartitionsWithIndex(
    lambda idx, it: [(idx, sum(1 for _ in it))]
).toDF(["partition_id", "record_count"]).show()

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("VenomProteomics_PDC") \
    .config("spark.driver.memory", "4g") \
    .config("spark.sql.shuffle.partitions", "8") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")
print("Spark version :", spark.version)
print("Spark ready ✓")

clean_results = [r for r in parallel_results if r is not None]
df_features = pd.DataFrame(clean_results)

print("Shape    :", df_features.shape)
print("Columns  :", list(df_features.columns))
print("Species  :", df_features["species"].nunique())
df_features.head(3)

sdf = spark.createDataFrame(df_features)
sdf = sdf.repartition(8)
sdf.cache()

print("Total proteins  :", sdf.count())
print("Partitions      :", sdf.rdd.getNumPartitions())

print("\nRecords per partition:")
sdf.rdd.mapPartitionsWithIndex(
    lambda idx, it: [(idx, sum(1 for _ in it))]
).toDF(["partition_id", "record_count"]).show()

from pyspark.sql.functions import col, avg, count, max as spark_max, min as spark_min

print("=== MAP: protein_id + cysteine frequency ===")
sdf.rdd \
   .map(lambda r: (r["protein_id"], r["freq_C"])) \
   .toDF(["protein_id", "freq_C"]) \
   .show(5)

print("=== FILTER: sequence length > 50 AA ===")
sdf_filtered = sdf.filter(col("seq_length") > 50)
print("Proteins > 50 AA:", sdf_filtered.count())

print("=== GROUPBY: species-level statistics ===")
sdf_grouped = sdf.groupBy("species").agg(
    count("protein_id").alias("num_proteins"),
    avg("seq_length").alias("avg_length"),
    avg("freq_C").alias("avg_cysteine"),
    spark_max("seq_length").alias("max_length"),
    spark_min("seq_length").alias("min_length")
).orderBy("num_proteins", ascending=False)

sdf_grouped.show(10)

"""# feature file generation"""

df_features.to_csv("data/processed_features.csv", index=False)
sdf_grouped.toPandas().to_csv("data/species_summary.csv", index=False)

# Parquet
sdf.write.mode("overwrite").parquet("data/features_parquet")

print("Exported:")
print("  ✓ data/processed_features.csv     ← send to Person 2")
print("  ✓ data/species_summary.csv")
print("  ✓ data/features_parquet/")
print("  ✓ 03_Results/speedup_plot.png")

from google.colab import files
files.download("data/processed_features.csv")
print("Downloaded ✓  →  send this file to Person 2")

spark.stop()
print("Spark stopped ✓")
print("Person 1 complete!")

"""# **Installs**"""

!pip install scikit-learn seaborn matplotlib pandas numpy -q
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')

"""# **Load the data**"""

species_df = pd.read_csv("/content/data/species_summary.csv")

print(df.shape)
print(df.columns.tolist())
df.head(3)

"""# **Summary Statistics**"""

print(" Dataset Overview ")
print(f"Total proteins     : {len(df)}")
print(f"Unique species     : {df['species'].nunique()}")
print(f"Avg sequence length: {df['seq_length'].mean():.1f} AA")
print(f"Min / Max length   : {df['seq_length'].min()} / {df['seq_length'].max()}")
top_species = df['species'].value_counts().head(10)
print("\nTop 10 species:\n", top_species)

"""# **Visualizations**"""

plt.figure(figsize=(10, 5))
plt.hist(df['seq_length'], bins=80, color='steelblue', edgecolor='black')
plt.title("Distribution of Protein Sequence Lengths")
plt.xlabel("Sequence Length (AA)")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

"""# **Top 10 Species Bar Chart**"""

fig, ax = plt.subplots(figsize=(12, 5))
top_species.plot(kind='bar', ax=ax, color='coral', edgecolor='black')
ax.set_title("Top 10 Snake Species by Protein Count")
ax.set_xlabel("Species")
ax.set_ylabel("Number of Proteins")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig("species_barplot.png", dpi=150)
plt.show()

"""# **Amino Acid Frequency Heatmap**"""

aa_cols = [c for c in df.columns if c.startswith('freq_')]
species_top10 = df['species'].value_counts().head(10).index.tolist()
df_top = df[df['species'].isin(species_top10)]

heatmap_data = df_top.groupby('species')[aa_cols].mean()
heatmap_data.columns = [c.replace('freq_', '') for c in heatmap_data.columns]

plt.figure(figsize=(16, 6))
sns.heatmap(heatmap_data, cmap='YlOrRd', annot=False, linewidths=0.3)
plt.title("Mean Amino Acid Frequencies by Species (Top 10)")
plt.xlabel("Amino Acid")
plt.ylabel("Species")
plt.tight_layout()
plt.savefig("03_aa_heatmap.png", dpi=150)
plt.show()

"""# **Radar Chart (Cysteine-rich species comparison)**"""

import matplotlib.patches as mpatches

radar_metrics = ['avg_length', 'avg_cysteine', 'max_length']
top5 = species_df.nlargest(5, 'num_proteins')

fig, ax = plt.subplots(figsize=(8, 5))
x = np.arange(len(radar_metrics))
width = 0.15

for i, (_, row) in enumerate(top5.iterrows()):
    vals = [row[m] for m in radar_metrics]
    vals_norm = [v / max(species_df[m]) for v, m in zip(vals, radar_metrics)]
    ax.bar(x + i*width, vals_norm, width, label=row['species'][:20])

ax.set_xticks(x + width*2)
ax.set_xticklabels(['Avg Length', 'Avg Cysteine', 'Max Length'])
ax.set_title("Normalized Venom Protein Metrics — Top 5 Species")
ax.legend(fontsize=7)
plt.tight_layout()
plt.savefig("results/04_species_comparison.png", dpi=150)
plt.show()

"""# **KMeans Clustering**"""

aa_cols = [c for c in df.columns if c.startswith('freq_')]
X = df[aa_cols].fillna(0)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
inertias = []
K_range = range(2, 9)
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertias.append(km.inertia_)

plt.figure(figsize=(7, 4))
plt.plot(list(K_range), inertias, marker='o', color='purple')
plt.title("Elbow Method — Choosing K")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.tight_layout()
plt.savefig("results/05_elbow_plot.png", dpi=150)
plt.show()

"""# **Apply KMeans with best K**"""

# Apply KMeans with best K (usually 3–4 for this dataset)
BEST_K = 4
km_final = KMeans(n_clusters=BEST_K, random_state=42, n_init=10)
df['cluster'] = km_final.fit_predict(X_scaled)

print("Cluster sizes:")
print(df['cluster'].value_counts())

"""# **PCA + Cluster Plot**"""

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

df['pca1'] = X_pca[:, 0]
df['pca2'] = X_pca[:, 1]

plt.figure(figsize=(9, 6))
colors = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12']
for c in range(BEST_K):
    mask = df['cluster'] == c
    plt.scatter(df.loc[mask, 'pca1'], df.loc[mask, 'pca2'],
                alpha=0.3, s=10, label=f'Cluster {c}', color=colors[c])

plt.title(f"PCA of Toxin Proteins — {BEST_K} Clusters")
plt.xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% variance)")
plt.ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% variance)")
plt.legend()
plt.tight_layout()
plt.savefig("results/06_pca_clusters.png", dpi=150)
plt.show()

"""# **Biological Interpretation**

Cluster 0:Short proteins with high cysteine frequency. These are likely 3-finger toxins or disulfide-rich neurotoxins, common in cobras (Naja species).


Cluster 1:Long proteins with low cysteine. Likely phospholipase A2 or serine protease toxins seen in pit vipers (Crotalus).


Cluster 2/3:Mixed length, moderate cysteine. May represent metalloproteinases or multi-domain venom enzymes.



Species like Ophiophagus hannah (king cobra) show elevated cysteine frequency consistent with their neurotoxic venom profile. Crotalus adamanteus (eastern diamondback) has longer average proteins, matching their hemotoxic enzymes.
"""